version: "3.7"

services:
  postgres:
    ports:
      - 5432:5432

  redis:
    ports:
      - 6379:6379

  minio:
    ports:
      - 9000:9000

  messenger:
    ports:
      - 4222:4222
      - 8222:8222

  messagestore:
    ports:
      - 5433:5432

  mail:
    image: mailhog/mailhog
    restart: unless-stopped
    ports:
      - 1025:1025
      - 8025:8025
