version: "3.7"

services:
  postgres:
    image: postgres:11-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}

  redis:
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASS}
    volumes:
      - redisdata:/data

  minio:
    image: minio/minio
    command: server /export
    volumes:
      - miniodata:/export
      - minioconfig:/root/.minio
    environment:
      MINIO_ACCESS_KEY: ${MINIO_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET}

  messenger:
    image: nats-streaming:linux
    command: -cid nss --store sql --sql_driver postgres --sql_source "user=${MSG_STORE_USER} password=${MSG_STORE_PASS} dbname=${MSG_STORE_DB} host=messagestore port=5432 sslmode=disable"
    volumes:
      - ./config:/config
    depends_on:
      - "messagestore"

  messagestore:
    image: postgres:11-alpine
    volumes:
      - messagestoredata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${MSG_STORE_USER}
      POSTGRES_PASSWORD: ${MSG_STORE_PASS}
      POSTGRES_DB: ${MSG_STORE_DB}

volumes:
  pgdata:
  redisdata:
  miniodata:
  minioconfig:
  messagestoredata:
